plugins:
  - rubocop-rspec
  - rubocop-yard

AllCops:
  NewCops: enable

# Keep indentation consistent
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# Keep indentation consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Keep indentation consistent
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Keep indentation consistent
Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

# It's ok to have longer lines
Layout/LineLength:
  Max: 160

# Not all plugins use all keyword arguments, it's normal.
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# It's ok to have longer methods, while keeping readability.
Metrics/AbcSize:
  Max: 120

# It's ok to have longer methods, while keeping readability.
Metrics/BlockLength:
  Max: 60

# It's ok to have longer methods, while keeping readability.
Metrics/BlockNesting:
  Max: 5

# It's ok to have longer classes, while keeping readability.
Metrics/ClassLength:
  Max: 250

# It's ok to have longer methods, while keeping readability.
Metrics/CyclomaticComplexity:
  Max: 40

# It's ok to have longer methods, while keeping readability.
Metrics/MethodLength:
  Max: 100

# It's ok to have longer methods, while keeping readability.
Metrics/ModuleLength:
  Max: 140

# kwargs should not count towards max parameters list.
Metrics/ParameterLists:
  CountKeywordArgs: false

# It's ok to have longer methods, while keeping readability.
Metrics/PerceivedComplexity:
  Max: 40

# Some method names should have less than 3 characters
Naming/MethodParameterName:
  AllowedNames:
    # Cline has the concept of timestamps using ts
    - ts

# These tests are not describing any class or module
RSpec/DescribeClass:
  Exclude:
    - 'spec/scenarios/code_quality_spec.rb'
    - 'spec/scenarios/packaging_spec.rb'

# It's ok to have scenarios having multiple lines
RSpec/ExampleLength:
  Max: 210

# It's ok to have test scenarios having several expectations
RSpec/MultipleExpectations:
  Max: 100

# It's ok to have nested groups in RSpec.
RSpec/NestedGroups:
  Max: 5

# Some test files can output to stdout and stderr
RSpec/Output:
  Exclude:
    # This module handles test debug output
    - spec/cline_test/helpers/debug.rb
    # The Cline CLI stub should output for the tests
    - spec/cline_test/stubs/cline

# The Cline CLI stub shoud le able to eval specific scenarios
Security/Eval:
  Exclude:
    - spec/cline_test/stubs/cline

# I don't want to pollute my code with something that should be integrated in the language
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# I don't want to pollute my code with something that should be integrated in the language
Style/MutableConstant:
  Enabled: false
