#!/usr/bin/env ruby

# Check that a given tasks folder contains tasks that cline-rb is able to read and write

tasks_dir = ARGV[0]

raise 'Usage: compatibility_check_tasks <tasks_dir>' if tasks_dir.nil?

require 'cline'
require 'fileutils'
require 'tmpdir'

original_tasks = Cline::Tasks.from_dir(tasks_dir)
# Replicate the tasks dir into a temporary directory using cline-rb readers and writers
Dir.mktmpdir do |temp_dir|
  original_tasks.each do |task_name, task|
    puts "Save task #{task_name}"
    if task.messages
      task.messages.json_to_base_dir("#{temp_dir}/#{task_name}")
    else
      FileUtils.mkdir_p("#{temp_dir}/#{task_name}")
    end
  end
  # Load the temporary directory
  new_tasks = Cline::Tasks.from_dir(temp_dir)
  # Compare both
  if original_tasks == new_tasks
    puts 'Tasks compatibility check - Success'
  else
    puts 'Tasks compatibility check - Failure'
  end
end
